[project]
name = "audioblocks-stacks"
requirements = []

[contracts.artist-registry]
path = "contracts/artist-registry.clar"
clarity_version = 2
epoch = 2.4

[contracts.audioblocks-marketplace]
path = "contracts/audioblocks-marketplace.clar"
clarity_version = 2
epoch = 2.4

[repl]
costs_version = 2
